### ISSUE TITLE
Unable to install ros-crystal-pcl-conversions due to unmet dependencies

### ISSUE THREAD

**Issue by bit-pirate** [ros2/pcl_conversions#4]
... hence hindering me to install ros-crystal-desktop.

I'm running Ubuntu 18.04.2. Note that I have recently installed ros-melodic-desktop. Removed all packages, but still struggeling with the same issue.

I can imagine, that this is the wrong place for this issue. If so, please point me to the right repo/place to post this. I'm not familiar with organizing ros2 releases. Sorry.

**Comment by mjcarroll** [comment]
Can you put your full error output for your attempt to install `ros-crystal-pcl-conversions`?

**Comment by nuclearsandwich** [comment]
This is definitely working on 18.04.1. 18.04.2 is due to be released on Thursday, the same day as our next Crystal release and it's possible that a regression is present. 

@bit-pirate where are you getting the 18.04.2 environment? Can you please paste the full error message so we know what dependency conflicts you're seeing.

**Comment by clalancette** [comment]
I just tried to install `ros-crystal-pcl-conversions` on a fresh Ubuntu 18.04 VM installed from the daily ISO: http://cdimage.ubuntu.com/bionic/daily-live/current/ .  This installed just fine.

I then wiped out the VM, started a new one, and installed `ros-melodic-desktop` following the instructions at http://wiki.ros.org/melodic/Installation/Ubuntu.  I then installed `ros-crystal-pcl-conversions` using the "testing" repository at http://packages.ros.org/ros2-testing/ubuntu/.  That also succeeded.

So I think this is actually working here.  @bit-pirate , without more information, it's hard to tell what happened on your system, since it seems to be working for us.

Update: I also ran the demo_nodes_cpp talker/listener, the demo_nodes_py talker/listener, and the image_tools cam2image/showimage pair with the installation.  Things seemed happy.

**Comment by tfoote** [comment]
For debugging this finding the lowest level package that refuses to install is valuable. It's an unfortunately manual process to try installing each of the dependencies that states uninstallable. From there `apt-cache policy` for each one both failing to install and the conflict would be valuable.

**Comment by bit-pirate** [comment]
Please excuse the late follow-up.

@nuclearsandwich I got "my" 18.04.02 from the official repos.

@clalancette just re-installed melodic and still stuck at install crystal

@tfoote traced the conflict: ros-crystal-desktop -> ros-crystal-pcl-conversions -> libpcl-dev -> .... -> ended here:

```
[...]
The following packages have unmet dependencies:
 libvtk6-qt-dev : Depends: libvtk6-dev (= 6.3.0+dfsg1-11build1) but it is not going to be installed

$ apt-cache policy  libvtk6-qt-dev
libvtk6-qt-dev:
  Installed: (none)
  Candidate: 6.3.0+dfsg1-11build1
  Version table:
     6.3.0+dfsg1-11build1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

$ apt-cache policy libvtk6-dev
libvtk6-dev:
  Installed: (none)
  Candidate: 6.3.0+dfsg1-11build1
  Version table:
     6.3.0+dfsg1-11build1 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
```
The following packages have unmet dependencies:
 tk-dev : Depends: tk8.6-dev (>= 8.6.0-2) but it is not going to be installed

$ apt-cache policy tk-dev
tk-dev:
  Installed: (none)
  Candidate: 8.6.0+9
  Version table:
     8.6.0+9 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages

$ apt-cache policy tk8.6-dev
tk8.6-dev:
  Installed: (none)
  Candidate: 8.6.8-4
  Version table:
     8.6.8-4 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```
```
The following packages have unmet dependencies:
 libfontconfig1-dev : Depends: libfontconfig1 (= 2.12.6-0ubuntu2) but 2.12.6-0ubuntu2.3 is to be installed

$ apt-cache policy libfontconfig1-dev
libfontconfig1-dev:
  Installed: (none)
  Candidate: 2.12.6-0ubuntu2
  Version table:
     2.12.6-0ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Package

$ apt-cache policy libfontconfig1
libfontconfig1:
  Installed: 2.12.6-0ubuntu2.3
  Candidate: 2.12.6-0ubuntu2.3
  Version table:
 *** 2.12.6-0ubuntu2.3 100
        100 /var/lib/dpkg/status
     2.12.6-0ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Package
```

Is this info helping?

**Comment by clalancette** [comment]
```
$ apt-cache policy libfontconfig1
libfontconfig1:
  Installed: 2.12.6-0ubuntu2.3
  Candidate: 2.12.6-0ubuntu2.3
  Version table:
 *** 2.12.6-0ubuntu2.3 100
        100 /var/lib/dpkg/status
     2.12.6-0ubuntu2 500
        500 http://de.archive.ubuntu.com/ubuntu bionic/main amd64 Package
```

This seems to be your problem.  Somehow you have `libfontconfig1` version 2.12.6-0ubuntu2.3 installed, but I can't find that version in the official Ubuntu repositories (they all have version 2.12.6-0ubuntu2).  I'd suggest removing and reinstalling that package from the official repositories, which I think will clear up this problem.

**Comment by bit-pirate** [comment]
Thanks a lot everyone! I got it to work.

I suspect that the upgrade from 16.04 -> 18.04 might have caused some weird versions to be installed.

In case others run into the same issue:
After forcing the installation of the version from the main repo using

`$ sudo apt install -f libfontconfig1=2.12.6-0ubuntu2`

I was able to install `ros-crystal-desktop`.
